document.addEventListener("DOMContentLoaded", () => {
  const form = document.getElementById("player-form"), xInput = document.getElementById("player-x"), oInput = document.getElementById("player-o"), area = document.getElementById("match-area"), board = document.getElementById("board"), cells = [...document.querySelectorAll(".cell")], turn = document.getElementById("turn-indicator"), message = document.getElementById("game-message"), error = document.getElementById("form-error"), dialog = document.getElementById("result-dialog");
  let players, state, startedAt, finished = false, toastTimer;
  const wins = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
  const updateQuick = () => { const stats = GameStorage.getStats(); document.getElementById("quick-total").textContent = stats.total; document.getElementById("quick-draws").textContent = stats.draws; document.getElementById("quick-wins").textContent = stats.xWins + stats.oWins; };
  function startGame() { state = Array(9).fill(""); finished = false; startedAt = Date.now(); cells.forEach(c => { c.textContent = ""; c.className = "cell"; c.disabled = false; }); message.textContent = ""; renderTurn(); }
  function renderTurn() { const symbol = state.filter(Boolean).length % 2 ? "O" : "X"; turn.innerHTML = `<span class="turn-mark ${symbol.toLowerCase()}">${symbol}</span><span><b>${players[symbol]}</b>'s turn</span>`; }
  function showToast(text, isError = false) { const toast = document.getElementById("toast"); clearTimeout(toastTimer); toast.textContent = text; toast.className = `toast is-visible${isError ? " is-error" : ""}`; toastTimer = setTimeout(() => { toast.className = "toast"; }, 2800); }
  function complete(result, line = []) { finished = true; cells.forEach((cell, i) => { cell.disabled = true; if (line.includes(i)) cell.classList.add("winner"); }); const moves = state.filter(Boolean).length, winner = result === "draw" ? "" : players[result.toUpperCase()]; const game = { playerX: players.X, playerO: players.O, winner, result, playedAt: new Date().toISOString(), moves, durationSeconds: Math.max(1, Math.round((Date.now() - startedAt) / 1000)) }; if (!GameStorage.addGame(game)) { message.textContent = "Match finished, but it could not be saved in browser storage."; showToast("Game could not be saved", true); } else showToast("Game saved to your match history"); updateQuick(); document.getElementById("result-symbol").textContent = result === "draw" ? "=" : "🏆"; document.getElementById("result-symbol").className = `result-symbol ${result}`; document.getElementById("result-title").textContent = result === "draw" ? "It’s a draw" : `${winner} wins!`; document.getElementById("result-copy").textContent = result === "draw" ? `${moves} moves · A perfectly matched board.` : `Congratulations! ${moves} moves played · ${game.durationSeconds}s match`; setTimeout(() => dialog.showModal(), 450); }
  function play(index) { if (finished || state[index]) { if (state[index]) { message.textContent = "That square is already taken."; board.classList.add("shake"); setTimeout(() => board.classList.remove("shake"), 300); } return; } const symbol = state.filter(Boolean).length % 2 ? "O" : "X"; state[index] = symbol; cells[index].textContent = symbol; cells[index].classList.add(symbol.toLowerCase(), "placed"); const line = wins.find(([a,b,c]) => state[a] && state[a] === state[b] && state[a] === state[c]); if (line) return complete(symbol.toLowerCase(), line); if (state.every(Boolean)) return complete("draw"); renderTurn(); }
  form.addEventListener("submit", e => { e.preventDefault(); const x = xInput.value.trim(), o = oInput.value.trim(); if (!x || !o) { error.textContent = "Enter a name for both players to start."; return; } if (x.toLowerCase() === o.toLowerCase()) { error.textContent = "Use different names for each player."; return; } error.textContent = ""; players = { X: x, O: o }; form.classList.add("is-hidden"); area.classList.remove("is-hidden"); startGame(); });
  cells.forEach(cell => cell.addEventListener("click", () => play(Number(cell.dataset.index)))); document.getElementById("new-game-button").addEventListener("click", startGame); document.getElementById("play-again").addEventListener("click", () => { dialog.close(); startGame(); }); document.getElementById("dialog-close").addEventListener("click", () => dialog.close()); updateQuick();
});
